$ANSIBLE_VAULT;1.1;AES256
62353335363462323861313136353136366566366464383265613139323866373731393962316262
3339386234663261633562346432383130393831373732300a313965306539343235643938356366
39316431356565386661373336343163613265363666376535306266333065323361346533373430
3366343339373865390a663565356164353064346636346565383836393662313162613266336333
39626364383662646330643636316564386465633466363538333036333737366335346263643036
32353664363834366436373036363835633166326263363762353436643732643339613037323234
66353736333737373262386365393764663730643534633735643936643661623436626530346131
66376366613735633865383931363661633633383432613764313539653638663433623138623632
6264
